# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{xml_node_stream}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Durand"]
  s.date = %q{2010-02-07}
  s.email = %q{brian@embellishedvisions.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT_LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/xml_node_stream.rb",
     "lib/xml_node_stream/node.rb",
     "lib/xml_node_stream/parser.rb",
     "lib/xml_node_stream/parser/base.rb",
     "lib/xml_node_stream/parser/libxml_parser.rb",
     "lib/xml_node_stream/parser/nokogiri_parser.rb",
     "lib/xml_node_stream/parser/rexml_parser.rb",
     "lib/xml_node_stream/selector.rb",
     "spec/node_spec.rb",
     "spec/parser_spec.rb",
     "spec/selector_spec.rb",
     "spec/spec_helper.rb",
     "spec/test.xml",
     "spec/xml_node_stream_spec.rb",
     "xml_node_stream.gemspec"
  ]
  s.homepage = %q{http://github.com/bdurand/xml_node_stream}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple XML parser wrapper that provides the benefits of stream parsing with the ease of using document nodes.}
  s.test_files = [
    "spec/node_spec.rb",
     "spec/parser_spec.rb",
     "spec/selector_spec.rb",
     "spec/spec_helper.rb",
     "spec/xml_node_stream_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

